POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "James",
    "password": "123"
}

###

POST http://localhost:8000/api/user
Content-Type: application/json

{
    "username": "Tom",
    "password": "123",
    "email": "tom@example.com",
    "phoneNumber": "123 123 123",
    "department": "Teacher",
    "isAdmin": "true"
}

###
GET http://localhost:8000/api/user